### ISSUE TITLE
Error in generated file

### ISSUE THREAD

**Issue by llastkrakw** [k-paxian/dart-json-mapper#106]
Hi,

please i have an issue when i generated file, the function _initialiseRefectable() was absent. I don't know how to fix that.

![image](https://user-images.githubusercontent.com/49950314/103775323-2d14fd00-502e-11eb-8f0b-e508ce0dcc9b.png)

**Comment by k-paxian** [comment]
Most probably your app doesn't have any annotated classes yet.

**Comment by llastkrakw** [comment]
the content of build.yaml : 

![image](https://user-images.githubusercontent.com/49950314/103838324-1487ff80-508d-11eb-89c6-cf6e9fa7aaf7.png)

my class file : 

![image](https://user-images.githubusercontent.com/49950314/103838430-51ec8d00-508d-11eb-8e9c-04c3976fba69.png)

and the generated files came everytimes with this error

**Comment by k-paxian** [comment]
```yaml
targets:
  $default:
    builders:
      dart_json_mapper:
          generate_for:
            # here should be listed root app files having 'void main()' function 
            - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files
```

You've listed distinct model files in `generate_for` section, instead you should list main entry point for your app there.
There is no need to list out every single model file there.
