### ISSUE TITLE
Calling initializeJsonMapper() in main() function throws unhandled Exception

### ISSUE THREAD

**Issue by plantiword** [k-paxian/dart-json-mapper#123]
Hi,

I'm having a problem when running a simple program. I'm reusing the default counter app that flutter create.

It looks I'm trying to call initializeJsonMapper() in the wrong place. 

I tried three different options:
**1. Calling in main() before runApp:**
void main() { 
  initializeJsonMapper();
  runApp(MyApp());
}

If I call the initializeJsonMapper() method in the main function before runApp(), the app crashes with the following stack trace:

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Reflectable has not been initialized.
E/flutter (15305): Please make sure that the first action taken by your program
E/flutter (15305): in `main` is to call `initializeReflectable()`

**2. Calling in main() after runAp**
void main() { 
  runApp(MyApp());
  initializeJsonMapper();
}
If I place it after runApp(), I get the same exception:

**3. Not calling initializeJsonMapper() at all** 
I get an error when calling JsonMapper.serialize():

Bad state: Reflectable has not been initialized.
Please make sure that the first action taken by your program
in `main` is to call `initializeReflectable()`.

this is the offending code
print(JsonMapper.serialize(dmi));

and this is the initialization of dmi:
final DummyModel dmi = new DummyModel("value1", "value2");

I'm enclosing my dart files (both localted in /lib)

 and the build.yaml file in the attached zip.

Thanks in advance for any guidance.

[lib.zip](https://github.com/k-paxian/dart-json-mapper/files/6265275/lib.zip)

**Comment by k-paxian** [comment]
build.yaml: 🔴 
```yaml
targets:
  $default:
    builders:
      dart_json_mapper:
          generate_for:
          # here should be listed entry point files having 'void main()' function
            - lib/model_dummy.dart

```

Have you read this comment? **"# here should be listed entry point files having 'void main()' function"**
You've listed direct file with the model class, which doesn't have `main` function in it

Instead you should specify your `main.dart` file there

build.yaml:  🟢 
```yaml
targets:
  $default:
    builders:
      dart_json_mapper:
          generate_for:
          # here should be listed entry point files having 'void main()' function
            - lib/main.dart

```
