### ISSUE TITLE
It seems your class has not been annotated with @jsonSerializable

### ISSUE THREAD

**Issue by koteesy** [k-paxian/dart-json-mapper#149]
Hello, when i try deserialize/serialize json strings into mobx models, i get error:

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: It seems your class 'Test' has not been annotated with @jsonSerializable
#0      JsonMapper._deserializeObject
package:dart_json_mapper/src/mapper.dart:896
#1      JsonMapper.deserialize
package:dart_json_mapper/src/mapper.dart:43
#2      JsonMapper.fromJson
package:dart_json_mapper/src/mapper.dart:61
#3      main
package:androidx/main.dart:56
<asynchronous suspension>

```

Example:

```dart
import 'package:dart_json_mapper/dart_json_mapper.dart' show Json, jsonSerializable;
import 'package:mobx/mobx.dart';

part "test.g.dart";

@jsonSerializable
@Json(allowCircularReferences: 1)
class Test = TestBase with _$Test;

@jsonSerializable
@Json(allowCircularReferences: 1)
abstract class TestBase with Store {
  @observable
  String value;

  TestBase({required this.value});
}
```
Main:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  initializeReflectable();

  initializeJsonMapper(adapters: [mobXAdapter]);
  JsonMapper().useAdapter(mobXAdapter);
  
  final str = '''{"value": "123"}''';

  print(JsonMapper.fromJson<Test>(str));
}
```

build.yaml
```yaml
targets:
  $default:
    builders:
      dart_json_mapper:
          generate_for:
          # here should be listed entry point files having 'void main()' function
            - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - lib/main.dart
        options:
          formatted: true
```

Dependencies
```yaml
dart_json_mapper:
dart_json_mapper_mobx:
flutter_mobx: ^2.0.1
```

Dev dependencies
```yaml
build_runner:
mobx_codegen:
```
