### ISSUE TITLE
code generator builder watches only main.dart file

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [k-paxian/dart-json-mapper#156]
The code generator works only for those classes that is decaled or referenced only in ```main.dart``` file

I don't have any annotated classes in the ```main.dart```, All the annotated classes is decaled in another files and they are not watched at all from the code generator

main.dart
```dart
import 'package:flutter/material.dart';

import 'main.mapper.g.dart' show initializeJsonMapper;

void main() {
  initializeJsonMapper();

  runApp(MyApp());
}

```

main.mapper.g.dart
```dart
// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// ignore_for_file: invalid_language_version_override
// No output from reflectable, 'package:reflectable/reflectable.dart' not used.
final mainAdapter = JsonMapperAdapter(
  title: 'mainAdapter',
  url: 'package:qalzam/main.dart',
  valueDecorators: {

},
  enumValues: {

});

Future<JsonMapper> initializeJsonMapperAsync({Iterable<JsonMapperAdapter> adapters = const []}) => Future(() => initializeJsonMapper(adapters: adapters));

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  
  final allAdapters = [...adapters, mainAdapter];
  for (var adapter in allAdapters) {
    JsonMapper().useAdapter(adapter);
  }
  return JsonMapper();
}
```

As you see the generated code is empty, And it works only for every single annotated class that is referenced in ```main.dart``` 
 file.
I need the generator to watch the annotated classes in the entire project not in the ```main.dart``` file only

build.yaml
```yaml
targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          # here should be listed entry point files having 'void main()' function
          - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files

```

Please help @k-paxian
