### ISSUE TITLE
NoSuchCapabilityErrorImpl exception when building

### ISSUE THREAD

**Issue by fasterlars** [k-paxian/dart-json-mapper#194]
I have a small flutter project with several classes. The dart_json_mapper works fine on linux, but on a windows machine I cannot startup the project because of this exception:
`_NoSuchCapabilityErrorImpl (Requesting mirror on un-marked class, `superclass` of `.Location`)`
If I continue the execution, the same exception occurs on the next class.

I run 'flutter pub run build_runner watch --delete-conflicting-outputs' to make sure the main.mapper.g.dart file is up to date.

This is my Location class:

```
import 'package:dart_json_mapper/dart_json_mapper.dart';

@JsonSerializable()
class Location {
  String? id;
  String? name;
  bool newsletter = false;
}
```

pubspec.yaml
  ```
dart_json_mapper: ^2.2.5+3
  dart_json_mapper_flutter: ^2.0.1
```
  
  
build.yaml
```
targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
        # here should be listed entry point files having 'void main()' function
          - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files

```

Thanks!
