### ISSUE TITLE
Is this library may work with inheritance and generics?

### ISSUE THREAD

**Issue by ValeriusGC** [k-paxian/dart-json-mapper#2]
Hi! 
The fact is i tried to work with
```
@jsonSerializable
class Base<T> {
  final T value;
  Base(this.value);
}

@jsonSerializable
class Derived extends Base<String>{
  Derived(String value) : super(value);
}
```
and just simply with 
```
@jsonSerializable
class Base {
  final String value;

  Base(this.value);
}

@jsonSerializable
class Derived extends Base{
  Derived(String value) : super(value);
}
```
and got the same errors:
```
NoSuchMethodError: The getter 'reflectedType' was called on null.
  Receiver: null
  Tried calling: reflectedType
  dart:core/runtime/libobject_patch.dart 50:5        Object.noSuchMethod
  package:dart_json_mapper/json_mapper.dart 228:62   JsonMapper.enumeratePublicFields
  package:dart_json_mapper/json_mapper.dart 355:5    JsonMapper.serializeObject
  package:dart_json_mapper/json_mapper.dart 45:37    JsonMapper.serialize
  bin/test/undostacktest.dart 33:22                  main.<fn>
  package:test_api/src/backend/declarer.dart 168:27  Declarer.test.<fn>.<fn>.<fn>
```

my `.yaml` is like

```
dependencies:
  json_annotation: ^1.0.0
dev_dependencies:
  build_runner: ^0.10.1+1
  dart_json_mapper: ^1.0.8
  test: ^1.5.1+1

```
