### ISSUE TITLE
Ability to find @jsonSerializable in part files

### ISSUE THREAD

**Issue by AntiqPeace** [k-paxian/dart-json-mapper#61]
I am using this library for some time and recently I had a look at the package `Freezed`.

Then, I looked into following issues:
[https://github.com/k-paxian/dart-json-mapper/issues/45](https://github.com/k-paxian/dart-json-mapper/issues/45)

[https://github.com/rrousselGit/freezed/issues/96](https://github.com/rrousselGit/freezed/issues/96)

I tried to combine these both, but ended up with failure. I want to use both of these libraries.

I tried to get this working and I **figured out something.** 

Basically, there are 2 problems:

1). Freezed package generates _actual class and its members_ in a separate, private class. So, dart-json-mapper can't access the class. (This can be solved by manually renaming the generated class, or by improving the Freezed package itself.)

2). Moreover, the Freezed package generates this private class in its `part` file (`.freezed.dart`). 
Here, I found that, `dart-json-mapper` can't access any class, which is present in a `part` file. Since it can't find, it can't generate the reflection code.

This problem (of part file) is not only related with Freezed package. I also tried by creating another simple / plain class in a part file and annotated it with `@jsonSerializable`, but it did not generate code for this class.

So, is there any possibility [ or trick ;) ] that dart-json-mapper can access the classes stored and annotated in part files.

I am migrating all my classes to Freezed, but at the same time, don't want to lose the flexibility of dart-json-mapper...

**Comment by innocentalone** [comment]
@AntiqPeace I agree with you.

**Comment by k-paxian** [comment]
If you'll look at unit tests here
https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/test/_test.dart
you'll notice that all of them are connected as **parts**, So this statement:

> So, is there any possibility [ or trick ;) ] that dart-json-mapper can access the classes stored and 
> annotated in part files.

Is not reflecting the reality.

My guess is that it's an issue in the **ordering** of code generation. You should make sure `Freezed` generation pass will be triggered *before* 'reflectable' pass.

My another guess is that could be possible configured at `build.yaml`

```yaml
targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
      reflectable:
        generate_for:
          - lib/main.dart
```
