### ISSUE TITLE
List and serialization not working without adapters

### ISSUE THREAD

**Issue by merlinofcha0s** [k-paxian/dart-json-mapper#87]
Hello,
In fact the deserialization of list and enum are not working without custom adapters, maybe I miss something.
The deserialization doesn't throw exceptions but the enum values are null even if there are some values in the JSON

I notice that : 

<img width="821" alt="Capture d’écran 2020-10-19 à 09 35 10" src="https://user-images.githubusercontent.com/6643835/96416733-ad2a8400-11f0-11eb-8a0d-10fa5b54eb25.png">

The value of the enum come back null from invokeGetter method.

so here is my code :

The model class :
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';
import '../pack/pack_model.dart';

@jsonSerializable
class Card {

  @JsonProperty(name: 'id')
  final int id;

  @JsonProperty(name: 'display')
  final String display;

  @JsonProperty(name: 'valueToSort')
  final String valueToSort;

  @JsonProperty(name: 'valueType', enumValues: ValueType.values)
  final ValueType valueType;

  @JsonProperty(name: 'sortingType', enumValues: SortingType.values)
  final SortingType sortingType;

  @JsonProperty(name: 'order')
  final int order;

  @JsonProperty(name: 'pack')
  final Pack pack;

 const Card (
     this.id,
        this.display,
        this.valueToSort,
        this.valueType,
        this.sortingType,
        this.order,
        this.pack,
    );

@override
String toString() {
    return 'Card{'+
    'id: $id,' +
        'display: $display,' +
        'valueToSort: $valueToSort,' +
        'valueType: $valueType,' +
        'sortingType: $sortingType,' +
        'order: $order,' +
        'pack: $pack,' +
    '}';
   }

@override
bool operator == (Object other) =>
    identical(this, other) ||
    other is Card &&
    id == other.id ;


@override
int get hashCode =>
    id.hashCode ;
}


@jsonSerializable
@Json(enumValues: ValueType.values)
enum ValueType {
    DATE ,
    NUMBER ,
    STRING
}

@jsonSerializable
@Json(enumValues: SortingType.values)
enum SortingType {
    NATURAL ,
    MANUAL
}
```

The main.dart
```dart
import 'package:sortyapp/environment.dart';
import 'package:flutter/material.dart';
import 'app.dart';
import 'main.mapper.g.dart' show initializeJsonMapper;
import 'mapper.dart';


void main() {
  Constants.setEnvironment(Environment.DEV);
  initializeJsonMapper();
  configMapper();
  runApp(SortyappApp());
}
```

The mapper : 

```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';
import 'package:sortyapp/shared/models/user.dart';
import 'package:sortyapp/entities/answer/answer_model.dart';
import 'package:sortyapp/entities/card/card_model.dart';
import 'package:sortyapp/entities/pack/pack_model.dart';
import 'package:sortyapp/entities/profile/profile_model.dart';
import 'package:sortyapp/entities/question/question_model.dart';
import 'package:sortyapp/entities/reference_xp/reference_xp_model.dart';
import 'package:sortyapp/entities/rule/rule_model.dart';
import 'package:sortyapp/entities/theme/theme_model.dart';
import 'package:sortyapp/entities/theme_score/theme_score_model.dart';
import 'package:sortyapp/entities/user_pack/user_pack_model.dart';

void configMapper() {
  JsonMapper().useAdapter(JsonMapperAdapter(valueDecorators: {
         typeOf<List<User>>(): (value) => value.cast<User>(),
          typeOf<List<Answer>>(): (value) => value.cast<Answer>(),
          typeOf<List<Card>>(): (value) => value.cast<Card>(),
          typeOf<List<Pack>>(): (value) => value.cast<Pack>(),
          typeOf<List<Profile>>(): (value) => value.cast<Profile>(),
          typeOf<List<Question>>(): (value) => value.cast<Question>(),
          typeOf<List<ReferenceXp>>(): (value) => value.cast<ReferenceXp>(),
          typeOf<List<Rule>>(): (value) => value.cast<Rule>(),
          typeOf<List<Theme>>(): (value) => value.cast<Theme>(),
          typeOf<List<ThemeScore>>(): (value) => value.cast<ThemeScore>(),
          typeOf<List<UserPack>>(): (value) => value.cast<UserPack>(),
          // jhipster-merlin-needle-mapper-list-add
 }, converters: {Enum: enumConverterShort}));
}
```

Can you tell me if it's a configuration problem ?

**Comment by k-paxian** [comment]
Could you please add more info, for instance the very bottom content of your `main.mapper.g.dart`
and `build.yaml` config, and project folders structure. Thanks

**Comment by merlinofcha0s** [comment]
Sure !

main.mapper.g.dart : 

```
void _initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}

final mainAdapter = JsonMapperAdapter(
  title: 'mainAdapter',
  url: 'package:sortyapp/main.dart',
  valueDecorators: {

});

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, mainAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}
```

Build.yaml : 

```
name: sortyapp
description: sortyapp flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.0
  http: 0.12.2
  dart_json_mapper: 1.6.3
  dart_json_mapper_flutter: 1.0.2
  flutter_secure_storage: 3.3.5
  url_launcher: 5.7.2
  datetime_picker_formfield: 1.0.0

  #BLoC pattern related
  formz: 0.3.2
  equatable: 1.2.5
  flutter_bloc: 6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
```

The folder structure : 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/6643835/96420983-7c4d4d80-11f6-11eb-8342-71ce3e8f8240.png">
